version: '3'
services:
  mongo:
    image: "mongo:4.0.4"
    container_name: "mongo4"
    ports:
      - '27017-27019:27017-27019'

  website-client:
    env_file:
      - ./.env
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - 3000:3000

  nginx:
    env_file:
      - ./.env
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: "nginx"
    depends_on:
      - website-client
    ports:
      - '3000:80'
