version: "3"
services:
  mongo:
    image: "mongo:4.0.4"
    container_name: "mongo-rmd-local"
    ports:
      - "28019:27017"
  # app:
  #   image: "keyjs-v1:latest"
  #   container_name: "keyjs"
  #   ports:
  #     - '3000:3000'
  # website-client:
  #   env_file:
  #     - ./.env
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   links:
  #     - mongo
  #   ports:
  #     - 3000:3000
  # nginx:
  #   env_file:
  #     - ./.env
  #   build:
  #     context: ./nginx/
  #     dockerfile: Dockerfile
  #   container_name: "nginx"
  #   depends_on:
  #     - website-client
  #   ports:
  #     - '3000:80'
